services:
  app:
    build:
      context: .
      dockerfile: ./deployment/docker/prod/Dockerfile
    # deploy:
    #   mode: replicated
    #   replicas: 3
    restart: always
    ports:
      - 3000:3000
