name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Lint, build and test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run lint &
          npm run typecheck &
          npm run format:check
          wait

      - name: Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
